### ISSUE TITLE
 cannot import name 'six'

### ISSUE THREAD

**Issue by tcurdt** [giovannicoppola/alfred-convert#7]
Any clue what might be the problem?

```
http_proxy=
https_proxy=
Traceback (most recent call last):
  File "/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/convert.py", line 19, in <module>
    from pint import UnitRegistry, UndefinedUnitError, DimensionalityError
  File "/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/pint/__init__.py", line 17, in <module>
    import pkg_resources
  File "/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/pkg_resources/__init__.py", line 57, in <module>
    from pkg_resources.extern import six
ImportError: cannot import name 'six' from 'pkg_resources.extern' (/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/pkg_resources/extern/__init__.py)
[15:56:23.105] Convert[Script Filter] Queuing argument '10 eur usd'
[15:56:23.253] Convert[Script Filter] Script with argv '10 eur usd' finished
[15:56:23.259] ERROR: Convert[Script Filter] Code 1: .
```

**Comment by tcurdt** [comment]
duplicate of https://github.com/giovannicoppola/alfred-convert/issues/6

**Comment by SALMANKHAN222coll** [comment]
http_proxy= https_proxy= Traceback (most recent call last): File "/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/convert.py", line 19, in <module> from pint import UnitRegistry, UndefinedUnitError, DimensionalityError File "/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/pint/__init__.py", line 17, in <module> import pkg_resources File "/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/pkg_resources/__init__.py", line 57, in <module> from pkg_resources.extern import six ImportError: cannot import name 'six' from 'pkg_resources.extern' (/Users/tcurdt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.880A0F6F-E844-4720-A9F4-76D08D052454/pkg_resources/extern/__init__.py) [15:56:23.105] Convert[Script Filter] Queuing argument '10 eur usd' [15:56:23.253] Convert[Script Filter] Script with argv '10 eur usd' finished [15:56:23.259] ERROR: Convert[Script Filter] Code 1: .

**Comment by SALMANKHAN222coll** [comment]
Sweet no Sweet without sweet
